# Generated by Django 5.2 on 2025-04-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('velas', 'Velas'), ('perfumes', 'Perfumes')], default='General', max_length=20),
            preserve_default=False,
        ),
    ]
